apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-rp
  name: udagram-rp
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: udagram-rp
  type: LoadBalancer
