apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-feed
  name: udagram-feed
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: udagram-feed

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-users
  name: udagram-users
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: udagram-users
